---
name: ChunkLoader
main: blugin\chunkloader\ChunkLoader
version: 2.2.3
api: [4.0.0]
authors: ['Blugin-team', 'PresentKim']
description: Load the chunk you want all the time!
depend: [libTranslator, libSubcommands]

permissions:
  chunkloader.cmd:
    description: ChunkLoader command
    default: op
    children:
      chunkloader.cmd.register:
        description: ChunkLoader command - register
        default: op
      chunkloader.cmd.unregister:
        description: ChunkLoader command - unregister
        default: op
      chunkloader.cmd.list:
        description: ChunkLoader command - list
        default: op
...