---
name: ChunkLoader
main: kim\present\chunkloader\ChunkLoader
version: 1.0.0
api: [3.0.0, 3.0.0-ALPHA12, 4.0.0]
author: PresentKim
website: https://github.com/PresentKim/ChunkLoader-PMMP
description: Load the chunk you want all the time!

permissions:
  chunkloader.cmd:
    description: ChunkLoader command
    default: op
    children:
      chunkloader.cmd.register:
        description: ChunkLoader command - register
        default: op
      chunkloader.cmd.unregister:
        description: ChunkLoader command - unregister
        default: op
      chunkloader.cmd.list:
        description: ChunkLoader command - list
        default: op
...