# Advanced configuration file for ChunkLoader plugin
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

settings:
  #Multi-language setting
  #Available: eng, kor
  language: "eng"


command:
  #Name of main command
  #You can change this to be what you want
  name: "chunkloader"

  #Permission of main command
  #You can change this to be what you want
  permission: "op"

  #Aliases of main command
  #You can add, replace, or remove them as you like
  aliases: ["cl", "chunkload"]

  children:
    #Setting of subcommands
    #Same as main command setting
    register:
      name: "Register"
      aliases: ["r", "add"]
      permission: "op"
    unregister:
      name: "Unregister"
      aliases: ["u", "remove"]
      permission: "op"
    clear:
      name: "Clear"
      aliases: ["c"]
      permission: "op"
    list:
      name: "List"
      aliases: ["l"]
      permission: "op"